[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "quarto-book-template"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
preview = "quarto preview mybook"
test = "quarto render mybook"

[dependencies]
quarto = ">=1.8.27,<2"
python = ">=3.14.6,<3.15"
jupyter = ">=1.1.1,<2"
r-base = ">=4.6.1,<4.7"
