project:
  type: book
  output-dir: docs

book:
  title: "Machine translation"
  author: "Deepthought"
  date: "2025-11-11"
  chapters:
    - index.qmd
    - part: "기초 도구"
      chapters:
        - linux_commands/linux_commands.qmd
        - linear_algebra/linear-algebra-book.qmd
    - part: "파이썬 프로그래밍 및 데이터 관리"
      chapters:
        - python_programming/PythonMastery.qmd
        - python_programming/Mastering_Python_for_Bioinformatics.qmd
        - python_programming/Python_for_Biologists_A_Complete_Programming_Course.qmd
        - python_programming/Managing_Your_Biological_Data_with_Python.qmd
        - python_programming/Streamlining_Your_Research_Laboratory_with_Python.qmd
    - part: "생명정보학 및 단백질 정보학"
      chapters:
        - bioinformatics/Sequence_Analysis_with_Biopython.qmd
        - bioinformatics/Large_Language_Models_in_Protein_Bioinformatics.qmd
        - bioinformatics/practical_bioinformatics.qmd
    - part: "머신러닝 및 인공지능"
      chapters:
        - machine_learning_ai/Deep_Learning_for_Biology_Harness_AI_to_Solve_Real_World_Biology_Problems.qmd
    - part: "AI 실제 적용"
      chapters:
        - ai_in_action/ai_in_action_complete.qmd
    - part: "생명정보학 실무 및 의학 응용"
      chapters:
        - applications/Bioinformatics_in_Cancer_and_Cancer_Therapy.md
        - applications/Bioinformatics_and_Computational_Biology_Solutions_Using_R_and_Bioconductor.md
        - applications/Bioinformatics_and_Drug_Discovery.md
    - part: "데이터 시각화"
      chapters:
        - dataviz/dataviz.qmd
    - part: "Rust 컴파일러 개발"
      chapters:
        - rust/rustc-dev-guide.qmd
    - part: "기타"
      chapters:
        - misc/The_simple_guide_to_minimalist.qmd



bibliography: references.bib

format:
  html:
    theme:
      - flatly
      - brand
    number-sections: false

execute:
  freeze: auto
