on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up pixi environment (Quarto, R, Python)
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: true
          activate-environment: default

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: mybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
